<form class="hide" id="create-room-<?= $category["category"]->getId(); ?>" action="/room-add" method="post">
    <input type="hidden" name="form-name" id="form-name" value="create-room" />
    <input type="hidden" name="category-id" id="category-id" value="<?= $category["category"]->getId(); ?>" />
    <fieldset>
        <label for="room-name">
            Nom du salon
        </label>
        <input type="text" name="room-name" id="room-name" />
    </fieldset>
    <button type="submit">Ajouter le salon</button>
</form>