<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Distorsion</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&family=Poppins:ital,wght@0,500;0,700;1,500;1,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/styles/css/style.css" />
    </head>
    <body>
        <header>
            <h1>Distorsion</h1>
        </header>
        <?php
            if($template !== "auth/login" && $template !== "auth/register" )
            {
                require "templates/partials/_sidebar.phtml";
            }
        ?>
        <?php require "templates/$template.phtml"; ?>
        <?php
        if($template !== "auth/login" && $template !== "auth/register" )
        {
            ?>
        <script type="module" src="/assets/js/index.js"></script>
        <?php
        }
        ?>
    </body>
</html>